/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.OnConfirmPostRequest;
import org.openapitools.client.model.OnInitPostRequest;
import org.openapitools.client.model.OnRatingPostRequest;
import org.openapitools.client.model.OnSearchPost200Response;
import org.openapitools.client.model.OnSearchPostRequest;
import org.openapitools.client.model.OnSelectPostRequest;
import org.openapitools.client.model.OnSupportPostRequest;
import org.openapitools.client.model.OnTrackPostRequest;
import org.openapitools.client.model.SearchPost200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class OndcBuyerAppApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OndcBuyerAppApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OndcBuyerAppApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for onCancelPost
     * @param onConfirmPostRequest Seller provides response to cancellation request (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onCancelPostCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onConfirmPostRequest;

        // create path and map variables
        String localVarPath = "/on_cancel";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onCancelPostValidateBeforeCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onCancelPostCall(onConfirmPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Send cancellation request_id with reasons list in case of cancellation request. Else send cancelled order object
     * @param onConfirmPostRequest Seller provides response to cancellation request (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onCancelPost(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onCancelPostWithHttpInfo(onConfirmPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Send cancellation request_id with reasons list in case of cancellation request. Else send cancelled order object
     * @param onConfirmPostRequest Seller provides response to cancellation request (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onCancelPostWithHttpInfo(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onCancelPostValidateBeforeCall(onConfirmPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Send cancellation request_id with reasons list in case of cancellation request. Else send cancelled order object
     * @param onConfirmPostRequest Seller provides response to cancellation request (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onCancelPostAsync(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onCancelPostValidateBeforeCall(onConfirmPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onConfirmPost
     * @param onConfirmPostRequest Seller confirms order (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onConfirmPostCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onConfirmPostRequest;

        // create path and map variables
        String localVarPath = "/on_confirm";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onConfirmPostValidateBeforeCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onConfirmPostCall(onConfirmPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Send active order object
     * @param onConfirmPostRequest Seller confirms order (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onConfirmPost(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onConfirmPostWithHttpInfo(onConfirmPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Send active order object
     * @param onConfirmPostRequest Seller confirms order (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onConfirmPostWithHttpInfo(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onConfirmPostValidateBeforeCall(onConfirmPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Send active order object
     * @param onConfirmPostRequest Seller confirms order (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onConfirmPostAsync(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onConfirmPostValidateBeforeCall(onConfirmPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onInitPost
     * @param onInitPostRequest Seller provides terms and conditions for an order (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onInitPostCall(OnInitPostRequest onInitPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onInitPostRequest;

        // create path and map variables
        String localVarPath = "/on_init";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onInitPostValidateBeforeCall(OnInitPostRequest onInitPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onInitPostCall(onInitPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Send order object with payment details updated
     * @param onInitPostRequest Seller provides terms and conditions for an order (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onInitPost(OnInitPostRequest onInitPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onInitPostWithHttpInfo(onInitPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Send order object with payment details updated
     * @param onInitPostRequest Seller provides terms and conditions for an order (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onInitPostWithHttpInfo(OnInitPostRequest onInitPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onInitPostValidateBeforeCall(onInitPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Send order object with payment details updated
     * @param onInitPostRequest Seller provides terms and conditions for an order (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onInitPostAsync(OnInitPostRequest onInitPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onInitPostValidateBeforeCall(onInitPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onRatingPost
     * @param onRatingPostRequest Seller provides response to rating provided by buyer (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onRatingPostCall(OnRatingPostRequest onRatingPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onRatingPostRequest;

        // create path and map variables
        String localVarPath = "/on_rating";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onRatingPostValidateBeforeCall(OnRatingPostRequest onRatingPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onRatingPostCall(onRatingPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Provide feedback on a service
     * @param onRatingPostRequest Seller provides response to rating provided by buyer (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onRatingPost(OnRatingPostRequest onRatingPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onRatingPostWithHttpInfo(onRatingPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Provide feedback on a service
     * @param onRatingPostRequest Seller provides response to rating provided by buyer (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onRatingPostWithHttpInfo(OnRatingPostRequest onRatingPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onRatingPostValidateBeforeCall(onRatingPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Provide feedback on a service
     * @param onRatingPostRequest Seller provides response to rating provided by buyer (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onRatingPostAsync(OnRatingPostRequest onRatingPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onRatingPostValidateBeforeCall(onRatingPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onSearchPost
     * @param onSearchPostRequest Sellers provide their catalog in response to buyer search (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onSearchPostCall(OnSearchPostRequest onSearchPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onSearchPostRequest;

        // create path and map variables
        String localVarPath = "/on_search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onSearchPostValidateBeforeCall(OnSearchPostRequest onSearchPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onSearchPostCall(onSearchPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Send catalog
     * @param onSearchPostRequest Sellers provide their catalog in response to buyer search (optional)
     * @return OnSearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public OnSearchPost200Response onSearchPost(OnSearchPostRequest onSearchPostRequest) throws ApiException {
        ApiResponse<OnSearchPost200Response> localVarResp = onSearchPostWithHttpInfo(onSearchPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Send catalog
     * @param onSearchPostRequest Sellers provide their catalog in response to buyer search (optional)
     * @return ApiResponse&lt;OnSearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OnSearchPost200Response> onSearchPostWithHttpInfo(OnSearchPostRequest onSearchPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onSearchPostValidateBeforeCall(onSearchPostRequest, null);
        Type localVarReturnType = new TypeToken<OnSearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Send catalog
     * @param onSearchPostRequest Sellers provide their catalog in response to buyer search (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onSearchPostAsync(OnSearchPostRequest onSearchPostRequest, final ApiCallback<OnSearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onSearchPostValidateBeforeCall(onSearchPostRequest, _callback);
        Type localVarReturnType = new TypeToken<OnSearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onSelectPost
     * @param onSelectPostRequest Seller provides quote for selected items (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onSelectPostCall(OnSelectPostRequest onSelectPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onSelectPostRequest;

        // create path and map variables
        String localVarPath = "/on_select";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onSelectPostValidateBeforeCall(OnSelectPostRequest onSelectPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onSelectPostCall(onSelectPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Send draft order object with quoted price for selected items
     * @param onSelectPostRequest Seller provides quote for selected items (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onSelectPost(OnSelectPostRequest onSelectPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onSelectPostWithHttpInfo(onSelectPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Send draft order object with quoted price for selected items
     * @param onSelectPostRequest Seller provides quote for selected items (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onSelectPostWithHttpInfo(OnSelectPostRequest onSelectPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onSelectPostValidateBeforeCall(onSelectPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Send draft order object with quoted price for selected items
     * @param onSelectPostRequest Seller provides quote for selected items (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onSelectPostAsync(OnSelectPostRequest onSelectPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onSelectPostValidateBeforeCall(onSelectPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onStatusPost
     * @param onConfirmPostRequest Seller provides status information for order (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onStatusPostCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onConfirmPostRequest;

        // create path and map variables
        String localVarPath = "/on_status";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onStatusPostValidateBeforeCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onStatusPostCall(onConfirmPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Fetch the status of a Service
     * @param onConfirmPostRequest Seller provides status information for order (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onStatusPost(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onStatusPostWithHttpInfo(onConfirmPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Fetch the status of a Service
     * @param onConfirmPostRequest Seller provides status information for order (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onStatusPostWithHttpInfo(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onStatusPostValidateBeforeCall(onConfirmPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Fetch the status of a Service
     * @param onConfirmPostRequest Seller provides status information for order (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onStatusPostAsync(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onStatusPostValidateBeforeCall(onConfirmPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onSupportPost
     * @param onSupportPostRequest Seller provides Contact Support details (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onSupportPostCall(OnSupportPostRequest onSupportPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onSupportPostRequest;

        // create path and map variables
        String localVarPath = "/on_support";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onSupportPostValidateBeforeCall(OnSupportPostRequest onSupportPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onSupportPostCall(onSupportPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Contact Support
     * @param onSupportPostRequest Seller provides Contact Support details (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onSupportPost(OnSupportPostRequest onSupportPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onSupportPostWithHttpInfo(onSupportPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Contact Support
     * @param onSupportPostRequest Seller provides Contact Support details (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onSupportPostWithHttpInfo(OnSupportPostRequest onSupportPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onSupportPostValidateBeforeCall(onSupportPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Contact Support
     * @param onSupportPostRequest Seller provides Contact Support details (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onSupportPostAsync(OnSupportPostRequest onSupportPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onSupportPostValidateBeforeCall(onSupportPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onTrackPost
     * @param onTrackPostRequest Seller provides tracking details for an order (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onTrackPostCall(OnTrackPostRequest onTrackPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onTrackPostRequest;

        // create path and map variables
        String localVarPath = "/on_track";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onTrackPostValidateBeforeCall(OnTrackPostRequest onTrackPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onTrackPostCall(onTrackPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Send tracking details of an active order
     * @param onTrackPostRequest Seller provides tracking details for an order (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onTrackPost(OnTrackPostRequest onTrackPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onTrackPostWithHttpInfo(onTrackPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Send tracking details of an active order
     * @param onTrackPostRequest Seller provides tracking details for an order (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onTrackPostWithHttpInfo(OnTrackPostRequest onTrackPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onTrackPostValidateBeforeCall(onTrackPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Send tracking details of an active order
     * @param onTrackPostRequest Seller provides tracking details for an order (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onTrackPostAsync(OnTrackPostRequest onTrackPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onTrackPostValidateBeforeCall(onTrackPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for onUpdatePost
     * @param onConfirmPostRequest Seller provides response to order update (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onUpdatePostCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = onConfirmPostRequest;

        // create path and map variables
        String localVarPath = "/on_update";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "GatewaySubscriberAuth", "GatewaySubscriberAuthNew", "SubscriberAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call onUpdatePostValidateBeforeCall(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = onUpdatePostCall(onConfirmPostRequest, _callback);
        return localVarCall;

    }

    /**
     * 
     * Returns updated service with updated runtime object
     * @param onConfirmPostRequest Seller provides response to order update (optional)
     * @return SearchPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public SearchPost200Response onUpdatePost(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        ApiResponse<SearchPost200Response> localVarResp = onUpdatePostWithHttpInfo(onConfirmPostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Returns updated service with updated runtime object
     * @param onConfirmPostRequest Seller provides response to order update (optional)
     * @return ApiResponse&lt;SearchPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SearchPost200Response> onUpdatePostWithHttpInfo(OnConfirmPostRequest onConfirmPostRequest) throws ApiException {
        okhttp3.Call localVarCall = onUpdatePostValidateBeforeCall(onConfirmPostRequest, null);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Returns updated service with updated runtime object
     * @param onConfirmPostRequest Seller provides response to order update (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledgement of message received </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call onUpdatePostAsync(OnConfirmPostRequest onConfirmPostRequest, final ApiCallback<SearchPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = onUpdatePostValidateBeforeCall(onConfirmPostRequest, _callback);
        Type localVarReturnType = new TypeToken<SearchPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
