/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Scalar;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Circle
 */
public class CircleTest {
    private final Circle model = new Circle();

    /**
     * Model tests for Circle
     */
    @Test
    public void testCircle() {
        // TODO: test Circle
    }

    /**
     * Test the property 'gps'
     */
    @Test
    public void gpsTest() {
        // TODO: test gps
    }

    /**
     * Test the property 'radius'
     */
    @Test
    public void radiusTest() {
        // TODO: test radius
    }

}
