/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Billing;
import org.openapitools.client.model.Fulfillment;
import org.openapitools.client.model.OnInitPostRequestMessageOrderAddOnsInner;
import org.openapitools.client.model.OnInitPostRequestMessageOrderItemsInner;
import org.openapitools.client.model.OnInitPostRequestMessageOrderOffersInner;
import org.openapitools.client.model.OnInitPostRequestMessageOrderProvider;
import org.openapitools.client.model.OnInitPostRequestMessageOrderProviderLocation;
import org.openapitools.client.model.Payment;
import org.openapitools.client.model.Quotation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OnInitPostRequestMessageOrder
 */
public class OnInitPostRequestMessageOrderTest {
    private final OnInitPostRequestMessageOrder model = new OnInitPostRequestMessageOrder();

    /**
     * Model tests for OnInitPostRequestMessageOrder
     */
    @Test
    public void testOnInitPostRequestMessageOrder() {
        // TODO: test OnInitPostRequestMessageOrder
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'providerLocation'
     */
    @Test
    public void providerLocationTest() {
        // TODO: test providerLocation
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'addOns'
     */
    @Test
    public void addOnsTest() {
        // TODO: test addOns
    }

    /**
     * Test the property 'offers'
     */
    @Test
    public void offersTest() {
        // TODO: test offers
    }

    /**
     * Test the property 'billing'
     */
    @Test
    public void billingTest() {
        // TODO: test billing
    }

    /**
     * Test the property 'fulfillment'
     */
    @Test
    public void fulfillmentTest() {
        // TODO: test fulfillment
    }

    /**
     * Test the property 'quote'
     */
    @Test
    public void quoteTest() {
        // TODO: test quote
    }

    /**
     * Test the property 'payment'
     */
    @Test
    public void paymentTest() {
        // TODO: test payment
    }

}
