/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.Descriptor;
import org.openapitools.client.model.Id;
import org.openapitools.client.model.ItemQuantity;
import org.openapitools.client.model.Price;
import org.openapitools.client.model.Time;
import org.openapitools.client.model.Value;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OnSelectPostRequestMessageOrderItemsInner
 */
public class OnSelectPostRequestMessageOrderItemsInnerTest {
    private final OnSelectPostRequestMessageOrderItemsInner model = new OnSelectPostRequestMessageOrderItemsInner();

    /**
     * Model tests for OnSelectPostRequestMessageOrderItemsInner
     */
    @Test
    public void testOnSelectPostRequestMessageOrderItemsInner() {
        // TODO: test OnSelectPostRequestMessageOrderItemsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'parentItemId'
     */
    @Test
    public void parentItemIdTest() {
        // TODO: test parentItemId
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'fulfillmentId'
     */
    @Test
    public void fulfillmentIdTest() {
        // TODO: test fulfillmentId
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'rateable'
     */
    @Test
    public void rateableTest() {
        // TODO: test rateable
    }

    /**
     * Test the property 'matched'
     */
    @Test
    public void matchedTest() {
        // TODO: test matched
    }

    /**
     * Test the property 'related'
     */
    @Test
    public void relatedTest() {
        // TODO: test related
    }

    /**
     * Test the property 'recommended'
     */
    @Test
    public void recommendedTest() {
        // TODO: test recommended
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

}
