/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Price
 */
public class PriceTest {
    private final Price model = new Price();

    /**
     * Model tests for Price
     */
    @Test
    public void testPrice() {
        // TODO: test Price
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'estimatedValue'
     */
    @Test
    public void estimatedValueTest() {
        // TODO: test estimatedValue
    }

    /**
     * Test the property 'computedValue'
     */
    @Test
    public void computedValueTest() {
        // TODO: test computedValue
    }

    /**
     * Test the property 'listedValue'
     */
    @Test
    public void listedValueTest() {
        // TODO: test listedValue
    }

    /**
     * Test the property 'offeredValue'
     */
    @Test
    public void offeredValueTest() {
        // TODO: test offeredValue
    }

    /**
     * Test the property 'minimumValue'
     */
    @Test
    public void minimumValueTest() {
        // TODO: test minimumValue
    }

    /**
     * Test the property 'maximumValue'
     */
    @Test
    public void maximumValueTest() {
        // TODO: test maximumValue
    }

}
