/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.Category;
import org.openapitools.client.model.Descriptor;
import org.openapitools.client.model.Fulfillment;
import org.openapitools.client.model.Item;
import org.openapitools.client.model.Offer;
import org.openapitools.client.model.Payment;
import org.openapitools.client.model.ProviderLocationsInner;
import org.openapitools.client.model.Time;
import org.openapitools.client.model.Value;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Provider
 */
public class ProviderTest {
    private final Provider model = new Provider();

    /**
     * Model tests for Provider
     */
    @Test
    public void testProvider() {
        // TODO: test Provider
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'fulfillments'
     */
    @Test
    public void fulfillmentsTest() {
        // TODO: test fulfillments
    }

    /**
     * Test the property 'payments'
     */
    @Test
    public void paymentsTest() {
        // TODO: test payments
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'offers'
     */
    @Test
    public void offersTest() {
        // TODO: test offers
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'exp'
     */
    @Test
    public void expTest() {
        // TODO: test exp
    }

    /**
     * Test the property 'rateable'
     */
    @Test
    public void rateableTest() {
        // TODO: test rateable
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
