/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Billing;
import org.openapitools.client.model.Fulfillment;
import org.openapitools.client.model.OnInitPostRequestMessageOrderAddOnsInner;
import org.openapitools.client.model.OnInitPostRequestMessageOrderItemsInner;
import org.openapitools.client.model.OnInitPostRequestMessageOrderOffersInner;
import org.openapitools.client.model.OnInitPostRequestMessageOrderProvider;
import org.openapitools.client.model.OnInitPostRequestMessageOrderProviderLocation;
import org.openapitools.client.model.Payment;
import org.openapitools.client.model.Quotation;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OnInitPostRequestMessageOrder
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-21T15:31:26.696+05:30[Asia/Kolkata]")
public class OnInitPostRequestMessageOrder {
  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  private OnInitPostRequestMessageOrderProvider provider;

  public static final String SERIALIZED_NAME_PROVIDER_LOCATION = "provider_location";
  @SerializedName(SERIALIZED_NAME_PROVIDER_LOCATION)
  private OnInitPostRequestMessageOrderProviderLocation providerLocation;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<OnInitPostRequestMessageOrderItemsInner> items = null;

  public static final String SERIALIZED_NAME_ADD_ONS = "add_ons";
  @SerializedName(SERIALIZED_NAME_ADD_ONS)
  private List<OnInitPostRequestMessageOrderAddOnsInner> addOns = null;

  public static final String SERIALIZED_NAME_OFFERS = "offers";
  @SerializedName(SERIALIZED_NAME_OFFERS)
  private List<OnInitPostRequestMessageOrderOffersInner> offers = null;

  public static final String SERIALIZED_NAME_BILLING = "billing";
  @SerializedName(SERIALIZED_NAME_BILLING)
  private Billing billing;

  public static final String SERIALIZED_NAME_FULFILLMENT = "fulfillment";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT)
  private Fulfillment fulfillment;

  public static final String SERIALIZED_NAME_QUOTE = "quote";
  @SerializedName(SERIALIZED_NAME_QUOTE)
  private Quotation quote;

  public static final String SERIALIZED_NAME_PAYMENT = "payment";
  @SerializedName(SERIALIZED_NAME_PAYMENT)
  private Payment payment;

  public OnInitPostRequestMessageOrder() {
  }

  public OnInitPostRequestMessageOrder provider(OnInitPostRequestMessageOrderProvider provider) {
    
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OnInitPostRequestMessageOrderProvider getProvider() {
    return provider;
  }


  public void setProvider(OnInitPostRequestMessageOrderProvider provider) {
    this.provider = provider;
  }


  public OnInitPostRequestMessageOrder providerLocation(OnInitPostRequestMessageOrderProviderLocation providerLocation) {
    
    this.providerLocation = providerLocation;
    return this;
  }

   /**
   * Get providerLocation
   * @return providerLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OnInitPostRequestMessageOrderProviderLocation getProviderLocation() {
    return providerLocation;
  }


  public void setProviderLocation(OnInitPostRequestMessageOrderProviderLocation providerLocation) {
    this.providerLocation = providerLocation;
  }


  public OnInitPostRequestMessageOrder items(List<OnInitPostRequestMessageOrderItemsInner> items) {
    
    this.items = items;
    return this;
  }

  public OnInitPostRequestMessageOrder addItemsItem(OnInitPostRequestMessageOrderItemsInner itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OnInitPostRequestMessageOrderItemsInner> getItems() {
    return items;
  }


  public void setItems(List<OnInitPostRequestMessageOrderItemsInner> items) {
    this.items = items;
  }


  public OnInitPostRequestMessageOrder addOns(List<OnInitPostRequestMessageOrderAddOnsInner> addOns) {
    
    this.addOns = addOns;
    return this;
  }

  public OnInitPostRequestMessageOrder addAddOnsItem(OnInitPostRequestMessageOrderAddOnsInner addOnsItem) {
    if (this.addOns == null) {
      this.addOns = new ArrayList<>();
    }
    this.addOns.add(addOnsItem);
    return this;
  }

   /**
   * Get addOns
   * @return addOns
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OnInitPostRequestMessageOrderAddOnsInner> getAddOns() {
    return addOns;
  }


  public void setAddOns(List<OnInitPostRequestMessageOrderAddOnsInner> addOns) {
    this.addOns = addOns;
  }


  public OnInitPostRequestMessageOrder offers(List<OnInitPostRequestMessageOrderOffersInner> offers) {
    
    this.offers = offers;
    return this;
  }

  public OnInitPostRequestMessageOrder addOffersItem(OnInitPostRequestMessageOrderOffersInner offersItem) {
    if (this.offers == null) {
      this.offers = new ArrayList<>();
    }
    this.offers.add(offersItem);
    return this;
  }

   /**
   * Get offers
   * @return offers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OnInitPostRequestMessageOrderOffersInner> getOffers() {
    return offers;
  }


  public void setOffers(List<OnInitPostRequestMessageOrderOffersInner> offers) {
    this.offers = offers;
  }


  public OnInitPostRequestMessageOrder billing(Billing billing) {
    
    this.billing = billing;
    return this;
  }

   /**
   * Get billing
   * @return billing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Billing getBilling() {
    return billing;
  }


  public void setBilling(Billing billing) {
    this.billing = billing;
  }


  public OnInitPostRequestMessageOrder fulfillment(Fulfillment fulfillment) {
    
    this.fulfillment = fulfillment;
    return this;
  }

   /**
   * Get fulfillment
   * @return fulfillment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Fulfillment getFulfillment() {
    return fulfillment;
  }


  public void setFulfillment(Fulfillment fulfillment) {
    this.fulfillment = fulfillment;
  }


  public OnInitPostRequestMessageOrder quote(Quotation quote) {
    
    this.quote = quote;
    return this;
  }

   /**
   * Get quote
   * @return quote
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Quotation getQuote() {
    return quote;
  }


  public void setQuote(Quotation quote) {
    this.quote = quote;
  }


  public OnInitPostRequestMessageOrder payment(Payment payment) {
    
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Payment getPayment() {
    return payment;
  }


  public void setPayment(Payment payment) {
    this.payment = payment;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnInitPostRequestMessageOrder onInitPostRequestMessageOrder = (OnInitPostRequestMessageOrder) o;
    return Objects.equals(this.provider, onInitPostRequestMessageOrder.provider) &&
        Objects.equals(this.providerLocation, onInitPostRequestMessageOrder.providerLocation) &&
        Objects.equals(this.items, onInitPostRequestMessageOrder.items) &&
        Objects.equals(this.addOns, onInitPostRequestMessageOrder.addOns) &&
        Objects.equals(this.offers, onInitPostRequestMessageOrder.offers) &&
        Objects.equals(this.billing, onInitPostRequestMessageOrder.billing) &&
        Objects.equals(this.fulfillment, onInitPostRequestMessageOrder.fulfillment) &&
        Objects.equals(this.quote, onInitPostRequestMessageOrder.quote) &&
        Objects.equals(this.payment, onInitPostRequestMessageOrder.payment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, providerLocation, items, addOns, offers, billing, fulfillment, quote, payment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnInitPostRequestMessageOrder {\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    providerLocation: ").append(toIndentedString(providerLocation)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    addOns: ").append(toIndentedString(addOns)).append("\n");
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("    billing: ").append(toIndentedString(billing)).append("\n");
    sb.append("    fulfillment: ").append(toIndentedString(fulfillment)).append("\n");
    sb.append("    quote: ").append(toIndentedString(quote)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("provider");
    openapiFields.add("provider_location");
    openapiFields.add("items");
    openapiFields.add("add_ons");
    openapiFields.add("offers");
    openapiFields.add("billing");
    openapiFields.add("fulfillment");
    openapiFields.add("quote");
    openapiFields.add("payment");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OnInitPostRequestMessageOrder
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (OnInitPostRequestMessageOrder.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in OnInitPostRequestMessageOrder is not found in the empty JSON string", OnInitPostRequestMessageOrder.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OnInitPostRequestMessageOrder.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OnInitPostRequestMessageOrder` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `provider`
      if (jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) {
        OnInitPostRequestMessageOrderProvider.validateJsonObject(jsonObj.getAsJsonObject("provider"));
      }
      // validate the optional field `provider_location`
      if (jsonObj.get("provider_location") != null && !jsonObj.get("provider_location").isJsonNull()) {
        OnInitPostRequestMessageOrderProviderLocation.validateJsonObject(jsonObj.getAsJsonObject("provider_location"));
      }
      JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
      if (jsonArrayitems != null) {
        // ensure the json data is an array
        if (!jsonObj.get("items").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
        }

        // validate the optional field `items` (array)
        for (int i = 0; i < jsonArrayitems.size(); i++) {
          OnInitPostRequestMessageOrderItemsInner.validateJsonObject(jsonArrayitems.get(i).getAsJsonObject());
        };
      }
      JsonArray jsonArrayaddOns = jsonObj.getAsJsonArray("add_ons");
      if (jsonArrayaddOns != null) {
        // ensure the json data is an array
        if (!jsonObj.get("add_ons").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `add_ons` to be an array in the JSON string but got `%s`", jsonObj.get("add_ons").toString()));
        }

        // validate the optional field `add_ons` (array)
        for (int i = 0; i < jsonArrayaddOns.size(); i++) {
          OnInitPostRequestMessageOrderAddOnsInner.validateJsonObject(jsonArrayaddOns.get(i).getAsJsonObject());
        };
      }
      JsonArray jsonArrayoffers = jsonObj.getAsJsonArray("offers");
      if (jsonArrayoffers != null) {
        // ensure the json data is an array
        if (!jsonObj.get("offers").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `offers` to be an array in the JSON string but got `%s`", jsonObj.get("offers").toString()));
        }

        // validate the optional field `offers` (array)
        for (int i = 0; i < jsonArrayoffers.size(); i++) {
          OnInitPostRequestMessageOrderOffersInner.validateJsonObject(jsonArrayoffers.get(i).getAsJsonObject());
        };
      }
      // validate the optional field `billing`
      if (jsonObj.get("billing") != null && !jsonObj.get("billing").isJsonNull()) {
        Billing.validateJsonObject(jsonObj.getAsJsonObject("billing"));
      }
      // validate the optional field `fulfillment`
      if (jsonObj.get("fulfillment") != null && !jsonObj.get("fulfillment").isJsonNull()) {
        Fulfillment.validateJsonObject(jsonObj.getAsJsonObject("fulfillment"));
      }
      // validate the optional field `quote`
      if (jsonObj.get("quote") != null && !jsonObj.get("quote").isJsonNull()) {
        Quotation.validateJsonObject(jsonObj.getAsJsonObject("quote"));
      }
      // validate the optional field `payment`
      if (jsonObj.get("payment") != null && !jsonObj.get("payment").isJsonNull()) {
        Payment.validateJsonObject(jsonObj.getAsJsonObject("payment"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OnInitPostRequestMessageOrder.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OnInitPostRequestMessageOrder' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OnInitPostRequestMessageOrder> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OnInitPostRequestMessageOrder.class));

       return (TypeAdapter<T>) new TypeAdapter<OnInitPostRequestMessageOrder>() {
           @Override
           public void write(JsonWriter out, OnInitPostRequestMessageOrder value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OnInitPostRequestMessageOrder read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OnInitPostRequestMessageOrder given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OnInitPostRequestMessageOrder
  * @throws IOException if the JSON string is invalid with respect to OnInitPostRequestMessageOrder
  */
  public static OnInitPostRequestMessageOrder fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OnInitPostRequestMessageOrder.class);
  }

 /**
  * Convert an instance of OnInitPostRequestMessageOrder to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

