/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Price;
import org.openapitools.client.model.QuotationBreakupInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes a quote
 */
@ApiModel(description = "Describes a quote")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-21T15:31:26.696+05:30[Asia/Kolkata]")
public class Quotation {
  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Price price;

  public static final String SERIALIZED_NAME_BREAKUP = "breakup";
  @SerializedName(SERIALIZED_NAME_BREAKUP)
  private List<QuotationBreakupInner> breakup = null;

  public static final String SERIALIZED_NAME_TTL = "ttl";
  @SerializedName(SERIALIZED_NAME_TTL)
  private String ttl;

  public Quotation() {
  }

  public Quotation price(Price price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Price getPrice() {
    return price;
  }


  public void setPrice(Price price) {
    this.price = price;
  }


  public Quotation breakup(List<QuotationBreakupInner> breakup) {
    
    this.breakup = breakup;
    return this;
  }

  public Quotation addBreakupItem(QuotationBreakupInner breakupItem) {
    if (this.breakup == null) {
      this.breakup = new ArrayList<>();
    }
    this.breakup.add(breakupItem);
    return this;
  }

   /**
   * Get breakup
   * @return breakup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<QuotationBreakupInner> getBreakup() {
    return breakup;
  }


  public void setBreakup(List<QuotationBreakupInner> breakup) {
    this.breakup = breakup;
  }


  public Quotation ttl(String ttl) {
    
    this.ttl = ttl;
    return this;
  }

   /**
   * Describes duration as per ISO8601 format
   * @return ttl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Describes duration as per ISO8601 format")

  public String getTtl() {
    return ttl;
  }


  public void setTtl(String ttl) {
    this.ttl = ttl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Quotation quotation = (Quotation) o;
    return Objects.equals(this.price, quotation.price) &&
        Objects.equals(this.breakup, quotation.breakup) &&
        Objects.equals(this.ttl, quotation.ttl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, breakup, ttl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Quotation {\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    breakup: ").append(toIndentedString(breakup)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("price");
    openapiFields.add("breakup");
    openapiFields.add("ttl");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Quotation
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (Quotation.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in Quotation is not found in the empty JSON string", Quotation.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Quotation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Quotation` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `price`
      if (jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull()) {
        Price.validateJsonObject(jsonObj.getAsJsonObject("price"));
      }
      JsonArray jsonArraybreakup = jsonObj.getAsJsonArray("breakup");
      if (jsonArraybreakup != null) {
        // ensure the json data is an array
        if (!jsonObj.get("breakup").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `breakup` to be an array in the JSON string but got `%s`", jsonObj.get("breakup").toString()));
        }

        // validate the optional field `breakup` (array)
        for (int i = 0; i < jsonArraybreakup.size(); i++) {
          QuotationBreakupInner.validateJsonObject(jsonArraybreakup.get(i).getAsJsonObject());
        };
      }
      if ((jsonObj.get("ttl") != null && !jsonObj.get("ttl").isJsonNull()) && !jsonObj.get("ttl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ttl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ttl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Quotation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Quotation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Quotation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Quotation.class));

       return (TypeAdapter<T>) new TypeAdapter<Quotation>() {
           @Override
           public void write(JsonWriter out, Quotation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Quotation read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Quotation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Quotation
  * @throws IOException if the JSON string is invalid with respect to Quotation
  */
  public static Quotation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Quotation.class);
  }

 /**
  * Convert an instance of Quotation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

