/*
 * ONDC Protocol Core API
 * ONDC Protocol Core API specification. This is an adaptation of Beckn Core version 0.9.3
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetCancellationReasonsPostRequest;
import org.openapitools.client.model.GetFeedbackFormPostRequest;
import org.openapitools.client.model.SearchPost200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SellerAppMetaApisApi
 */
@Disabled
public class SellerAppMetaApisApiTest {

    private final SellerAppMetaApisApi api = new SellerAppMetaApisApi();

    /**
     * Get cancellation reasons from the Seller App
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCancellationReasonsPostTest() throws ApiException {
        GetCancellationReasonsPostRequest getCancellationReasonsPostRequest = null;
        SearchPost200Response response = api.getCancellationReasonsPost(getCancellationReasonsPostRequest);
        // TODO: test validations
    }

    /**
     * Request a feedback form from the Seller App
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedbackFormPostTest() throws ApiException {
        GetFeedbackFormPostRequest getFeedbackFormPostRequest = null;
        SearchPost200Response response = api.getFeedbackFormPost(getFeedbackFormPostRequest);
        // TODO: test validations
    }

    /**
     * Get a list of categories that can be rated by the Seller App
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRatingCategoriesPostTest() throws ApiException {
        GetCancellationReasonsPostRequest getCancellationReasonsPostRequest = null;
        SearchPost200Response response = api.getRatingCategoriesPost(getCancellationReasonsPostRequest);
        // TODO: test validations
    }

    /**
     * Get return reasons from the Seller App
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReturnReasonsPostTest() throws ApiException {
        GetCancellationReasonsPostRequest getCancellationReasonsPostRequest = null;
        SearchPost200Response response = api.getReturnReasonsPost(getCancellationReasonsPostRequest);
        // TODO: test validations
    }

}
